### ISSUE TITLE
Want to edit this app

### ISSUE THREAD

**Issue by masterpradipg** [i-p-tel/sipdroid#1013]
Hello !
i am newbie to this. I want to edit this app for my college project . Should i used Android Studio or eclipse or what ?i tried both android studio and eclipse but unable to compile ? so plz help me load and modify this app? my question is what IDE should i used to edit this ? or how can i edit and build this app?

**Comment by w1570187062** [comment]
hello!
This app can use IDE both android studio and eclipse,it's simple to use ecipse ,because it selsf is make by eclipse,but i recommend use android studio,thanks

**Comment by aries255** [comment]
Have you tried it on android studio?
